<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-16T20:44:02 IST" name="Failed suite [Suite]" finished-at="2024-05-16T20:44:07 IST" duration-ms="5468">
    <groups>
    </groups>
    <test started-at="2024-05-16T20:44:02 IST" name="Test(failed)" finished-at="2024-05-16T20:44:07 IST" duration-ms="5468">
      <class name="com.standalone.SauceInvalidLoginTest">
        <test-method is-config="true" signature="init()[pri:0, instance:com.standalone.SauceInvalidLoginTest@703580bf]" started-at="2024-05-16T20:44:02 IST" name="init" finished-at="2024-05-16T20:44:05 IST" duration-ms="3665" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="invalidLoginTest()[pri:0, instance:com.standalone.SauceInvalidLoginTest@703580bf]" started-at="2024-05-16T20:44:05 IST" name="invalidLoginTest" finished-at="2024-05-16T20:44:07 IST" duration-ms="1466" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error Message Did not Match expected [Epic sadface: Sorry, this user has been locked out.dsd] but found [Epic sadface: Sorry, this user has been locked out.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error Message Did not Match expected [Epic sadface: Sorry, this user has been locked out.dsd] but found [Epic sadface: Sorry, this user has been locked out.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.standalone.SauceInvalidLoginTest.invalidLoginTest(SauceInvalidLoginTest.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.standalone.SauceInvalidLoginTest@703580bf]" started-at="2024-05-16T20:44:07 IST" name="tearDown" finished-at="2024-05-16T20:44:07 IST" duration-ms="293" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.standalone.SauceInvalidLoginTest -->
    </test> <!-- Test(failed) -->
  </suite> <!-- Failed suite [Suite] -->
</testng-results>
